name: CHPB web app JMeter tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: JMeter Test
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: test/*.jmx
          args: "--loglevel INFO"
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.jtl
